### PR TITLE
WIP Mobile line sharer

### PR DESCRIPTION
**Pull request by bogas04**
Swipe to left to access the sharer. Currently it works only for mixed view.

* [ ] split mode
* [ ] use navigator.share, WhatsApp otherwise
* [ ] Different analytics
* [ ] Demo mode to educate users

### CODE REVIEW

**Comment by saintsoldierx** [comment]
@bogas04 Can you update us on this?

**Comment by bogas04** [comment]
Won't be able to work on it, if someone wants to pick up from here it'll be nice :D

**Comment by AkalUstat** [comment]
@saintsoldierx what was the main obj of this pr? Any mockups of how this should look. Might be able to take it up in a few weeks

**Comment by AkalUstat** [comment]
@saintsoldierx is this something we still want to/ need to work on?

**Comment by saintsoldierx** [comment]
@AkalUstat yes!

**Pull request closed without merging**
