### PR TITLE
Feature hukamnama audio - #1261

### PR DESCRIPTION
**Pull request by gurjit03**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

image

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by tarunsingh5** [comment]
i feel like the UI here is very confusing the left/right arrows change the day but the play button in between plays it, can we make that more clear somehow?

**Comment by tarunsingh5** [comment]
are we storing audio for past days?

**Comment by saintsoldierx** [comment]
No. Not at this time. The player will be removed for past days.

**Comment by saintsoldierx** [comment]
image
I will be changing the layout so audio player moves to bottom. Rewind and forward buttons are pretty standard for this function.

**Pull request merged**
