### PR TITLE
Feature fuzzy search

### PR DESCRIPTION
**Pull request by gurjit03**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

This PR is in reference to issue #141 
<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by saintsoldierx** [comment]
Nice. 

- Move MAIN LETTER SEARCH above FULL WORD (GURMUKHI)
- Can the words in the results be highlighted?

**Comment by saintsoldierx** [comment]
@gurjit03 so it only highlights words that are together. What about words that are separate? 

image

**Comment by gurjit03** [comment]
@saintsoldierx veerji, what you have searched for ?

**Comment by saintsoldierx** [comment]
I typed in "bdn hr" and it came up with what i sent in screenshot @gurjit03

**Comment by saintsoldierx** [comment]
@gurjit03 resolve the conflicts please - this probably related to the graying out of gurbani issue - in this search type, gurbani should also not be grayed out.

**Comment by saintsoldierx** [comment]
Is this still WIP @gurjit03?

**Comment by gurjit03** [comment]
@saintsoldierx we need testing for it, so mentioned it as `draft`.

**Pull request merged**
