### PR TITLE
Fix local deploy warnings

### PR DESCRIPTION
**Pull request by rajkambo**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by rajkambo** [comment]
Took a while to find, but https://github.com/webpack/webpack/issues/7378 had a workaround (using `export type`) for how to export interfaces properly. Going to run the sanity tests after lunch so please don't merge yet.

**Comment by rajkambo** [comment]
@saintsoldierx I wasn't able to reproduce the last warning in the ticket https://github.com/KhalisFoundation/sttm-web/issues/815:

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
app (280 KiB)
chunks/vendor-5f4396f0b453524fbb96.js
app-5f4396f0b453524fbb96.js
```

and I checked the logs of the above dev deploy and didn't find it there either? so not sure if that is still an issue?

**Comment by saintsoldierx** [comment]
Thanks @rajkambo ! No worries about the last issue. Just making sure - this won't cause issues with unicode right?

**Comment by rajkambo** [comment]
No problem! And sorry forgot to comment about that. But it looks like we don’t have the “toggle Unicode” button anymore under fonts rights? We only have the option to set to Unicode or the other fonts, so that kind of rendered the toggle case unnecessary right?

**Comment by saintsoldierx** [comment]
Ahh yes you're right - it's not a toggle button, it is a list item under the FONTS dropdown. Thanks again @rajkambo !

**Pull request merged**
