### PR TITLE
Adds a print option to shabad

### PR DESCRIPTION
**Pull request by Gauravjeetsingh**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

Adds a print option
g3yoq-jwcob

Tested the print preview by saving it in pdf in following three browsers.
Safari: [safari-sttm.pdf](https://github.com/KhalisFoundation/sttm-web/files/3103940/safari-sttm.pdf)
Chrome: [chrome-sttm.pdf](https://github.com/KhalisFoundation/sttm-web/files/3103941/chrome-sttm.pdf)
Firefox: [firefox-sttm.pdf](https://github.com/KhalisFoundation/sttm-web/files/3103942/firefox-sttm.pdf)

### CODE REVIEW

**Comment by Gauravjeetsingh** [comment]
Things I need to work on:
- Getting a blank last page in firefox and safari occasionally.
- Code optimization (there is an existing todo in code to use Loop for all the share buttons)
- Responsiveness of share buttons.

**Comment by bogas04** [comment]
Let's get this done next? Seems like a low hanging fruit

**Comment by bogas04** [comment]
@Gauravjeetsingh What do you think?

**Comment by Gauravjeetsingh** [comment]
Yeah, sure, got other higher priority tasks, this got left behind. Will update the code, and push.

**Pull request merged**
