### PR TITLE
Adds line number in bani controller & switches to stg sttm api for dev

### PR DESCRIPTION
**Pull request by Gauravjeetsingh**
Dark mode:
Screenshot from 2020-07-08 21-13-42

Light mode:
Screenshot from 2020-07-08 21-14-31

Currently thinking of changing the line number background color for light mode.

### CODE REVIEW

**Comment by maneetpaul** [comment]
@saintsoldierx Can you take a look and provide input regarding colors? 

@Gauravjeetsingh can you also provide a screenshot for how it looks when the line has already been read?

**Comment by saintsoldierx** [comment]
image
.controller-shabad .line.active-slide .line-count {
    background-color: #1e3c51;
    color: #cae8f8;
}

**Comment by saintsoldierx** [comment]
In light mode, the greyed out ones look ok - maybe just give font color less opacity if already clicked on or it make it a dark grey.

**Comment by saintsoldierx** [comment]
image
.controller-shabad .line {
    background-color: rgb(0, 57, 98)

controller-shabad .line .line-count {
    background-color: #00253f;

image

**Comment by Gauravjeetsingh** [comment]
Updated colors:
Screenshot from 2020-07-10 14-28-17
Screenshot from 2020-07-10 14-26-15

**Comment by saintsoldierx** [comment]
Dark mode blue colors still a little off I feel. Is this ok @maneetpaul ?

**Comment by Gauravjeetsingh** [comment]
Updated the colors.

Light mode:
image

Dark mode:
image

**Pull request merged**
