### PR TITLE
Use search highlighting. Fix #523

### LINKED ISSUE #523: Highlighting the words in the results based on query in Larivaar mode
We have highlighting the search words on search results page which works great for non-larivaar mode. However, switching/using larivaar mode this feature does not work.

In all modes, let's have opacity of the highlighted words as 100 and those not part of the results as less (maybe 30).

image

### PR DESCRIPTION
**Pull request by bogas04**

### CODE REVIEW

**Comment by bogas04** [comment]
@tarunsingh5 could you see if the implementation is good enough? 

https://zeit.co/github/deployment?deploymentId=Sx8nV77gmBr8QSx8BxCP8hbx

**Comment by saintsoldierx** [comment]
Looks good to me guys.

**Comment by bogas04** [comment]
@tarunsingh5 @saintsoldierx did you check larivaar and assist mode as well?

**Comment by tarunsingh5** [comment]
@bogas04 hanji i did - looks great

**Pull request merged**
