### PR TITLE
Add new fonts for Gurbani

### PR DESCRIPTION
**Pull request by ekas**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by saintsoldierx** [comment]
Remove Raaj font for now please.

**Comment by ekas** [comment]
> Remove Raaj font for now please.

Okay @saintsoldierx veerji

**Comment by saintsoldierx** [comment]
@ekas just wondering if you had managed to do this yet?

**Comment by ekas** [comment]
> @ekas just wondering if you had managed to do this yet?

Yes veerji I have done it. But wasn't able to commit. Will to do it by EOD.

**Comment by ekas** [comment]
> > @ekas just wondering if you had managed to do this yet?
> 
> Yes veerji I have done it. But wasn't able to commit. Will to do it by EOD.

@saintsoldierx  Veerji, I have committed the chnages - Removed Raaj fonts and kept just one i.e. Prabhki. Please Review.

**Pull request merged**
