### PR TITLE
Automate Sanity Tests

### PR DESCRIPTION
**Pull request by bogas04**
Fix for #411 

* [x] Basic boilerplate code
* [x] Guru Granth Sahib Ji Check:
> Search: “qnjqnh”
> Confirm that “Teerath Naavan Jao..” appears
> Click next and previous to ensure you can browse shabads
* [x] Dasam Granth Sahib Check:
> Search: “sksls”
> Confirm that “Sach Kahoun Sun …” appears
> Click the shabad, click ang, confirm you can do next/prev arrows
* [x] Bhai Gurdaas Ji Check:
> Search: “nsls”
> Confirm that “Nakh Sis Lo...” appears
> Click split view, confirm it changes
* [ ] Unicode check:
> Toggle Unicode Button  - confirm output changes to unicode 
* [ ] Larivaar check:
> Toggle Larivaar Button -  confirm output changes to larivaar
> Toggle Larivaar Assist Button -  confirm output changes to larivaar assist
* [ ] Hamburger Menu Check (Mobile):
> Click on the hamburger menu (top right) - confirm it works
* [ ] Short Letter Search:
> Search “jh”
> Confirm that shorter results such as “jale hain” appear first in the results
* [ ] Keyboard Check:
> Make sure keyboard loads when clicking on the icon
> Check that clicking on “1” and “2” toggles between pages of the keyboard and works correctly
* [ ] Font Size Check:
> Make sure that font sizes can be changed under display options
* [ ] Split View Check:
When in split view change the font size (try various sizes), ensure that text doesn’t overlap
Check if Translation disappears when you load more results (and that all other settings remain as they should).
* [x] Make sure test suite runs server before running tests, and closes it after it's done.
* [ ] Make sure it's headless & snappy in test mode (rely on NODE_ENV=debug).

Demo:
ezgif com-optimize

### CODE REVIEW

**Comment by bogas04** [comment]
If anyone is interested to take this forward;

[Puppeteer Docs](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserfetcherplatform)

[Sanity Tests](http://bit.ly/sttm-sanity-tests)

**Comment by bogas04** [comment]
https://github.com/smooth-code/jest-puppeteer/blob/master/README.md

**Comment by bogas04** [comment]
@rajkambo Would you like to work on this? It'll be really cool to have this running on our CI.

**Comment by rajkambo** [comment]
Yeah for sure! I'll take a look 👍

**Pull request closed without merging**
