### PR TITLE
WIP: Add banners feature

### PR DESCRIPTION
**Pull request by gurpreet-hanjra**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [ ]  Ran `npm test` & fixed newly introduced lint errors.
* [ ]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by saintsoldierx** [comment]
@gurpreet-hanjra First draft looks good, can't wait to see the final version

**Comment by saintsoldierx** [comment]
@gurpreet-hanjra any updates?

**Comment by AkalUstat** [comment]
@saintsoldierx what is needed to complete this? Unsure how much is left

**Comment by saintsoldierx** [comment]
> @saintsoldierx what is needed to complete this? Unsure how much is left

I believe just the UI part, making it look how it is in the mock-up.

**Comment by AkalUstat** [comment]
finished in #938

**Pull request closed without merging**
