### PR TITLE
Github Action to add label when PR is approved

### PR DESCRIPTION
**Pull request by plug-n-play**
* [ ]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [ ]  Ran `npm test` & fixed newly introduced lint errors.
* [ ]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by plug-n-play** [comment]
I don't have access to settings for this project. Following needs to be done:
image

Once this is done, the `Merge pull request` button would be disabled until we have minimum 1 approval

**Comment by saintsoldierx** [comment]
Is this ready to be merged? @plug-n-play 
Can you review @ManjotS ?

**Comment by plug-n-play** [comment]
Yes @saintsoldierx - this is ready

**Comment by tsingh777** [comment]
I'm not seeing the usefulness of adding this github action. If a PR is approved, why does it it need a label? You can just open a PR to see if it's approved. 

For enforcing a PR needing approval, I would like that too (we have that for most of our repos), but its up to the dev team if they want to enforce that. @saintsoldierx @Gauravjeetsingh @gurjit03 what works best for you?

**Comment by saintsoldierx** [comment]
Thanks @tsingh777 - that really helped. I am not sure it is needed either tbh. Only person merging is me and I only do that after i have reviewed the PR or if someone else has already reviewed and approved. So may not really be necessity at this point but definitely appreciate the idea behind it.

**Pull request closed without merging**
