### PR TITLE
Update React and React-DOM

### PR DESCRIPTION
**Pull request by AkalUstat**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

This is to allow support for hooks later. (Updates to v16.13)

### CODE REVIEW

**Comment by AkalUstat** [comment]
The other testing libs in devDeps have moved to different repos/packages and they also need updating. I can do this in a separate pr if needed

**Comment by gurjit03** [comment]
@AkalUstat what other testing libraries you are referring to?

**Comment by AkalUstat** [comment]
jest-dom, dom-testing-library, react-testing-library have all moved to new packages. Other devDeps like babel stuff, lint etc need to update as well

**Comment by AkalUstat** [comment]
Ive smoke tested the deployment and it seems fine. Could someone else also verify?

**Pull request merged**
