### PR TITLE
Feature settings overhaul

### PR DESCRIPTION
**Pull request by gurjit03**
* [x]  Passed [sanity tests](http://bit.ly/sttm-sanity-tests).
* [x]  Ran `npm test` & fixed newly introduced lint errors.
* [x]  Checked console for errors.

<!-- New to markdown? Simply put an 'x' between [ ] to check it. Like [x] this. (No spaces).

### CODE REVIEW

**Comment by saintsoldierx** [comment]
We making any more progress on this @gurjit03 ?

**Comment by saintsoldierx** [comment]
@gurjit03 any more progress on this or should we merge and enhance in future PRs?

**Comment by gurjit03** [comment]
@saintsoldierx yes will be pushing some updates on this by end of tomorrow.

**Comment by saintsoldierx** [comment]
Need to check Vishraam settings, doesn't work at the moment

**Pull request merged**
